### ISSUE TITLE
Bug: If put to auto resume on tab focus. Video resumes on alt tab mode anywhere in the operating system.

### ISSUE THREAD

**Issue by Krinjon** [drodil/youtube_auto_pause#2]
Be it in different desktop or same desktop where the video is running. 
Steps 1. check auto pause on unfocus and check auto resume on focus.
 2. play video. 
 3. go out of foucs with alt tab or anything. Video pauses.
 4. do alt+tab (not necessarily to come back to the video) the video resume in the background. And keep playing as long as you are in alt tab mode. Also if you are in a different desktop.

**Comment by drodil** [comment]
Thanks for the bug report, I added a new feature for window unfocus/focus for the next 1.4.0 release. Hopefully I get to ship it tomorrow. Should fix this issue!

**Comment by drodil** [comment]
Could you retry with the latest version @Krinjon ? Thanks!

**Comment by Krinjon** [comment]
> Could you retry with the latest version @Krinjon ? Thanks!

the alt tab bug is still there. Also the video is resuming automatically in random interval if I keep it paused with space bar.

**Comment by Krinjon** [comment]
Feature Request/ Improvement: 
If you know potplayer auto resume feature it would be easier to explain. Pot player has the perfect autoresume autopause functions anywhere.
So in pot player if you pause using space bar and get out of window and come back if does not resume cause it assumes you wanted keep it pause. Video should not auto resume all the time. There should be some way to remember if the user paused the video , if yes dont auto resume let the user resume. And if user auto paused by moveing away from the video only then auto resume. 
I know a little bit of programming but never in javascript or chrome extension. So I am not sure if I can code it myself. Thats why I am just requesting feature. But i will see.

**Comment by drodil** [comment]
Hm. Weird. I cannot reproduce the alt+tab bug on my machine no matter what I do :D Also haven't seen automatic resuming randomly. Have to dig in more. 

For the feature request, it might be good addition but might need some listener to the player to catch when user is pausing it instead when it's paused programatically. Could you create another issue about that feature, would make it easier to follow up on these?

**Comment by Krinjon** [comment]
I tried to see when exactly video is resuming on its own. Cannot tell you how to reproduce. Also alt tab is happening 70% of time. Not always. Another thing, I use multiple users in chrome (to keep bookmarks and search history separate). Sometimes all different user at the same time open. While alt tab bug happens in one user and not the other. Its all just too random for me to point you to anything. Are you using chrome in mac or windows. Cause I am talking windows.
Only one thing I can say for sure if more than one or two windows are open other than chrome then alt tabing bug happens more frequently. I mean once it start it keeps happening on every alt tab. But the chance of starting the bug is higher like that. This bug was always there. Before 1.4 since the beginning. If it happens so frequently for me. Its weird that it does not happen to your machine at all.

**Comment by drodil** [comment]
Ok, I will try with multiple users, maybe that explains. Do you have the extension installed for both users? I have tried to reproduce this with mac and windows chrome but without luck. Let's see if multiple users could explain it.

**Comment by Krinjon** [comment]
yes. All of users have the extension.

**Comment by Krinjon** [comment]
I found the problem in my pc. I was running a virtual desktop switching app virtual-desktop-enhancer in the background. That was switching the desktop without switching the desktop. So window was getting focused without getting focused. Don't know how that can happen. Anyway that was the problem. Turned it off. 
The extension is working fine. Sorry for the trouble.
